<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $equipment = Equipment::create([
            'type' => 1,
            'name' => 'Behrigner X32 Compact',
            'price' => 100,
            'quantity' => 5,
            'imagePath' => 'x32compact.jpg',
            'imagePath2' => 'x32compact2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=IjDsF7UCgnY',
            'description' => 'Great mixer for medium gigs.',
            'info1' => '<td>Brand</td><td>Behringer</td>',
            'info2' => '<td>Mixer type</td><td>Digital</td>',
            'info3' => '<td>Number of channels</td><td>40</td>',
            'info4' => '<td>Power plug</td><td>IEC</td>',
            'info5' => '<td>Included</td><td>Power cord, earphones</td>',
            'feature1' => 'High quality MIDAS preamps',
            'feature2' => 'Two AES50 Inputs',
            'feature3' => 'Motorized faders',
        ]);

        $equipment = Equipment::create([
            'type' => 1,
            'name' => 'Yamaha CL5',
            'price' => 150,
            'quantity' => 3,
            'imagePath' => 'yamahacl5.jpg',
            'imagePath2' => 'yamahacl5_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=AnvXTyrqR_0',
            'description' => 'Mixer for large gigs and venues',
            'info1' => '<td>Brand</td><td>Yamaha</td>',
            'info2' => '<td>Mixer type</td><td>Digital</td>',
            'info3' => '<td>Number of channels</td><td>80</td>',
            'info4' => '<td>Power plug</td><td>IEC</td>',
            'info5' => '<td>Included</td><td>Power cord, earphones</td>',
            'feature1' => 'Over 50 sound effects available',
            'feature2' => 'Comapatiblity with DANTE interface',
            'feature3' => 'Motorized faders',
        ]);

        $equipment = Equipment::create([
            'type' => 1,
            'name' => 'Soundcraft UI16',
            'price' => 75,
            'quantity' => 10,
            'imagePath' => 'scui.jpg',
            'imagePath2' => 'scui2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=dgGQZlK-ieg',
            'description' => 'Compact mixer for small events',
            'info1' => '<td>Brand</td><td>Soundcraft</td>',
            'info2' => '<td>Mixer type</td><td>Digital</td>',
            'info3' => '<td>Number of channels</td><td>16</td>',
            'info4' => '<td>Power plug</td><td>12V DC</td>',
            'info5' => '<td>Included</td><td>Power supply, android tablet</td>',
            'feature1' => 'Wireless connection by Wi-Fi',
            'feature2' => 'Built in USB Player',
            'feature3' => 'Record option for USB Drive',
        ]);

        $equipment = Equipment::create([
            'type' => 1,
            'name' => 'Behrigner Xenyx X802',
            'price' => 50,
            'quantity' => 20,
            'imagePath' => 'xenyx.jpg',
            'imagePath2' => 'xenyx2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=7pq6QjojrEI',
            'description' => 'Mixer for presentations',
            'info1' => '<td>Brand</td><td>Behringer</td>',
            'info2' => '<td>Mixer type</td><td>Analogue</td>',
            'info3' => '<td>Number of channels</td><td>6</td>',
            'info4' => '<td>Power plug</td><td>AC</td>',
            'info5' => '<td>Included</td><td>Power supply</td>',
            'feature1' => 'Small size',
            'feature2' => '2 XLR mono channels, 2 Line In Stereo channels',
            'feature3' => 'Three band equalizer',
        ]);

        $equipmnet = Equipment::create([
            'type' => 2,
            'name' => 'JBL EON 610',
            'price' => 50,
            'quantity' => 8,
            'imagePath' => 'eon610.jpg',
            'imagePath2' => 'eon610_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=3dotOF1sbAA',
            'description' => 'Great active speaker',
            'info1' => '<td>Brand</td><td>JBL</td>',
            'info2' => '<td>Type</td><td>Active</td>',
            'info3' => '<td>Amplifier Power</td><td>1000 W</td>',
            'info4' => '<td>Power plug</td><td>IEC</td>',
            'info5' => '<td>Included</td><td>Power supply, tripod</td>',
            'feature1' => 'Two-way 10" speaker',
            'feature2' => 'Frequency range 52 Hz - 20 kHz',
            'feature3' => 'Built-in control via Bluetooth',
        ]);

        $equipmnet = Equipment::create([
            'type' => 2,
            'name' => 'JBL EON 612',
            'price' => 60,
            'quantity' => 8,
            'imagePath' => 'eon610.jpg',
            'imagePath2' => 'eon610_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=3dotOF1sbAA',
            'description' => 'Great active speaker',
            'info1' => '<td>Brand</td><td>JBL</td>',
            'info2' => '<td>Type</td><td>Active</td>',
            'info3' => '<td>Amplifier Power</td><td>1000 W</td>',
            'info4' => '<td>Power plug</td><td>IEC</td>',
            'info5' => '<td>Included</td><td>Power supply, tripod</td>',
            'feature1' => 'Two-way 12" speaker',
            'feature2' => 'Frequency range 48 Hz - 20 kHz',
            'feature3' => 'Built-in control via Bluetooth',
        ]);

        $equipmnet = Equipment::create([
            'type' => 2,
            'name' => 'JBL EON 615',
            'price' => 70,
            'quantity' => 8,
            'imagePath' => 'eon610.jpg',
            'imagePath2' => 'eon610_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=3dotOF1sbAA',
            'description' => 'Great active speaker',
            'info1' => '<td>Brand</td><td>JBL</td>',
            'info2' => '<td>Type</td><td>Active</td>',
            'info3' => '<td>Amplifier Power</td><td>1000 W</td>',
            'info4' => '<td>Power plug</td><td>IEC</td>',
            'info5' => '<td>Included</td><td>Power supply, tripod</td>',
            'feature1' => 'Two-way 15" speaker',
            'feature2' => 'Frequency range 39 Hz - 20 kHz',
            'feature3' => 'Built-in control via Bluetooth',
        ]);

        $equipmnet = Equipment::create([
            'type' => 3,
            'name' => 'Shure SM58-LCE',
            'price' => 40,
            'quantity' => 30,
            'imagePath' => 'sm58.jpg',
            'imagePath2' => 'sm58_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=NldhZGrFNeE',
            'description' => 'Legendary vocal microphone',
            'info1' => '<td>Brand</td><td>Shure</td>',
            'info2' => '<td>Microphone type</td><td>Dynamic</td>',
            'info3' => '<td>Characteristic</td><td>Cardioid</td>',
            'info4' => '<td>Connector</td><td>XLR</td>',
            'info5' => '<td>Frequency</td><td>50 - 15000 Hz</td>',
            'feature1' => 'Durable, steel cover',
            'feature2' => 'Frequency response matched to the vocal, with a brightened middle band and cut bass.',
            'feature3' => 'LCE version (without switch)',
        ]);
        $equipmnet = Equipment::create([
            'type' => 3,
            'name' => 'Shure SM58-SE',
            'price' => 40,
            'quantity' => 30,
            'imagePath' => 'sm58.jpg',
            'imagePath2' => 'sm58_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=NldhZGrFNeE',
            'description' => 'Legendary vocal microphone',
            'info1' => '<td>Brand</td><td>Shure</td>',
            'info2' => '<td>Microphone type</td><td>Dynamic</td>',
            'info3' => '<td>Characteristic</td><td>Cardioid</td>',
            'info4' => '<td>Connector</td><td>XLR</td>',
            'info5' => '<td>Frequency</td><td>50 - 15000 Hz</td>',
            'feature1' => 'Durable, steel cover',
            'feature2' => 'Frequency response matched to the vocal, with a brightened middle band and cut bass.',
            'feature3' => 'SE (with switch)',
        ]);
        $equipmnet = Equipment::create([
            'type' => 3,
            'name' => 'Shure SM58-SE',
            'price' => 40,
            'quantity' => 30,
            'imagePath' => 'sm58.jpg',
            'imagePath2' => 'sm58_2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=NldhZGrFNeE',
            'description' => 'Legendary vocal microphone',
            'info1' => '<td>Brand</td><td>Shure</td>',
            'info2' => '<td>Microphone type</td><td>Dynamic</td>',
            'info3' => '<td>Characteristic</td><td>Cardioid</td>',
            'info4' => '<td>Connector</td><td>XLR</td>',
            'info5' => '<td>Frequency</td><td>50 - 15000 Hz</td>',
            'feature1' => 'Durable, steel cover',
            'feature2' => 'Frequency response matched to the vocal, with a brightened middle band and cut bass.',
            'feature3' => 'SE (with switch)',
        ]);

        $equipmnet = Equipment::create([
            'type' => 3,
            'name' => 'Rode M5 Pair',
            'price' => 90,
            'quantity' => 30,
            'imagePath' => 'm5.jpg',
            'imagePath2' => 'm5.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=LsC6Xy31Els',
            'description' => 'Pair of condenser microphones',
            'info1' => '<td>Brand</td><td>Rode</td>',
            'info2' => '<td>Microhpone type</td><td>Condenser</td>',
            'info3' => '<td>Characteristic</td><td>Cardioid</td>',
            'info4' => '<td>Connector</td><td>XLR</td>',
            'info5' => '<td>Frequency</td><td>20 - 20000 Hz</td>',
            'feature1' => 'Durable, steel cover',
            'feature2' => '0.5 inch capsule',
            'feature3' => 'Rented as a pair',
        ]);

        $equipmnet = Equipment::create([
            'type' => 4,
            'name' => 'XLR Cable 1m',
            'price' => 10,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'Kabel XLR 1m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>1m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made XLR cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 4,
            'name' => 'XLR Cable 2.5m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'Kabel XLR 2.5m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>2.5m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made XLR cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 4,
            'name' => 'XLR Cable 5m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'Kabel XLR 1m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>5m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made XLR cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 4,
            'name' => 'XLR Cable 10m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'Kabel XLR 10m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>10m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made XLR cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 4,
            'name' => 'XLR Cable 20m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'Kabel XLR 1m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>20m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made XLR cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 5,
            'name' => 'GrandMA3',
            'price' => 800,
            'quantity' => 2,
            'imagePath' => 'grandma.jpg',
            'imagePath2' => 'grandma2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=1-FQVsgmDcY',
            'description' => 'Best DMX controller ever made. Operator must be also rented.',
            'info1' => '<td>Brand</td><td>MA Lighting</td>',
            'info2' => '<td>Number of channels</td><td>524 288 (1024 uniwersa)</td>',
            'info3' => '<td>Supported protocols</td><td>DMX, ArtNet, MIDI</td>',
            'info4' => '<td>Power plig</td><td>TrueOne</td>',
            'info5' => '<td>Included</td><td>Case</td>',
            'feature1' => 'Over 9000 effects available',
            'feature2' => 'New, optimized interface',
            'feature3' => 'Price includes lighting operator',
        ]);

        $equipmnet = Equipment::create([
            'type' => 5,
            'name' => 'GrandMA2',
            'price' => 200,
            'quantity' => 5,
            'imagePath' => 'grandma.jpg',
            'imagePath2' => 'grandma2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=W24lJjxXZPA',
            'description' => 'Popular DMX controller',
            'info1' => '<td>Brand</td><td>MA Lighting</td>',
            'info2' => '<td>Number of channels</td><td>524 288 (1024 universes)</td>',
            'info3' => '<td>Supported protocols</td><td>DMX, ArtNet, MIDI</td>',
            'info4' => '<td>Power plug</td><td>TrueOne</td>',
            'info5' => '<td>Included</td><td>Case</td>',
            'feature1' => 'Over 9000 effects available',
            'feature2' => 'Touch screens',
            'feature3' => 'Mechanical switches',
        ]);

        $equipmnet = Equipment::create([
            'type' => 6,
            'name' => 'Robe Pointe',
            'price' => 100,
            'quantity' => 200,
            'imagePath' => 'pointe.jpg',
            'imagePath2' => 'pointe2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=1rtD5i3m2Kg',
            'description' => 'Moving head 140W',
            'info1' => '<td>Brand</td><td>Robe</td>',
            'info2' => '<td>Power</td><td>140 W</td>',
            'info3' => '<td>Connector</td><td>DMX XLR 5pin</td>',
            'info4' => '<td>Power plug</td><td>TrueOne</td>',
            'info5' => '<td>Included</td><td>Case, power cord</td>',
            'feature1' => 'Wide lighting degree',
            'feature2' => 'Easy addressing via Bluetooth connection',
            'feature3' => 'Quiet motor',
        ]);
        $equipmnet = Equipment::create([
            'type' => 6,
            'name' => 'Flash PAR LED RGBW',
            'price' => 50,
            'quantity' => 300,
            'imagePath' => 'par.jpg',
            'imagePath2' => 'par2.jpg',
            'videoPath' => 'https://www.youtube.com/watch?v=Bp5tx8-hVnc',
            'description' => 'PAR LED RGB 9x13W',
            'info1' => '<td>Brand</td><td>Flash</td>',
            'info2' => '<td>Power</td><td>60W</td>',
            'info3' => '<td>Connector</td><td>DMX XLR 3pin</td>',
            'info4' => '<td>Power plug</td><td>PowerCon</td>',
            'info5' => '<td>Included</td><td>Power cord</td>',
            'feature1' => 'Wide lighting degree',
            'feature2' => 'Automated cooling mode',
            'feature3' => 'Built-in effects',
        ]);

        $equipmnet = Equipment::create([
            'type' => 7,
            'name' => 'DMX Cable 1m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'DMX Cable 1m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>1m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made DMX cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 7,
            'name' => 'DMX Cable 2.5m',
            'price' => 10,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'DMX Cable 2.5m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>2.5m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made DMX cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 7,
            'name' => 'DMX Cable 5m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'DMX Cable 5m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>5m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made DMX cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 7,
            'name' => 'DMX Cable 10m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'DMX Cable 10m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>10m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made DMX cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

        $equipmnet = Equipment::create([
            'type' => 7,
            'name' => 'DMX Cable 20m',
            'price' => 15,
            'quantity' => 200,
            'imagePath' => 'xlr.jpg',
            'imagePath2' => null,
            'videoPath' => null,
            'description' => 'DMX Cable 1m',
            'info1' => '<td>Brand</td><td>own</td>',
            'info2' => '<td>Connector brand</td><td>Neutrik</td>',
            'info3' => '<td>Cable length</td><td>1m</td>',
            'info4' => '<td>Connectors</td><td>XLR M - XLR F</td>',
            'info5' => null,
            'feature1' => 'Professionaly made DMX cable',
            'feature2' => 'Durable',
            'feature3' => 'Silvered XLR conectors',
        ]);

    }
}
